
# Old and not stable
#CHROME_FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland"
#ELECTRON_OZONE_PLATFORM_HINT="wayland"
#ELECTRON_USE_WAYLAND=1

# Old, don't needed now
#MOZ_ENABLE_WAYLAND=1

