__GLX_VENDOR_LIBRARY_NAME=nvidia
GBM_BACKEND=nvidia-drm
LIBVA_DRIVER_NAME=nvidia
CUDA_DISABLE_PERF_BOOST=1

# Not needed now
#__NV_DISABLE_EXPLICIT_SYNC=1
#__GL_MaxFramesAllowed=1

#__NV_PRIME_RENDER_OFFLOAD=1
